name: mobile_app
description: "NexPoket Crypto Wallet App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

# 🔥 FINAL ICON CONFIG (IMPORTANT FIX)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png

  adaptive_icon_background: "#0A0A23"
  adaptive_icon_foreground: assets/icon.png

  android_round_icon: true
  remove_alpha_ios: true   # 👈 NEW (important)
