name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # ✅ CLEAN
      - name: Clean project
        run: flutter clean

      # ✅ DEPENDENCIES
      - name: Install dependencies
        run: flutter pub get

      # ⚠️ ICONS (SAFE)
      - name: Generate App Icons
        run: dart run flutter_launcher_icons || true

      # ✅ SYNC AGAIN
      - name: Reinstall dependencies
        run: flutter pub get

      # 🔥 BUILD (VERBOSE FOR DEBUG)
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons --verbose

      # 🔍 DEBUG FILES
      - name: Debug Build Folder
        run: ls -R build || true

      # 🔍 FIND APK
      - name: Find APK
        run: find . -name "*.apk"

      # ✅ UPLOAD (AUTO SAFE)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nexpoket-apk
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/apk/**/*.apk
