name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 🔥 MOVE INTO PROJECT (CRITICAL FIX)
      - name: Go to project
        run: cd mobile_app

      # ✅ CLEAN
      - name: Clean project
        working-directory: mobile_app
        run: flutter clean

      # ✅ DEPENDENCIES
      - name: Install dependencies
        working-directory: mobile_app
        run: flutter pub get

      # ⚠️ ICONS SAFE
      - name: Generate App Icons
        working-directory: mobile_app
        run: dart run flutter_launcher_icons || true

      # 🔥 BUILD (FINAL FIX)
      - name: Build APK
        working-directory: mobile_app
        run: flutter build apk --release --no-tree-shake-icons --verbose

      # 🔍 DEBUG
      - name: Check files
        run: ls -R mobile_app/build || true

      # 🔍 FIND APK
      - name: Find APK
        run: find mobile_app -name "*.apk"

      # ✅ UPLOAD
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nexpoket-apk
          path: mobile_app/build/app/outputs/**/*.apk
